apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-example
spec:
  replicas: 2
  selector:
    app: rc-demo
  template:
    metadata:
      name: rc-demo
      labels:
        app: rc-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.10-alpine
        ports:
        - containerPort: 80
