apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: default
spec:
  containers:
  - name: jenkins
    image: jenkins
    ports:
      - containerPort: 8080
        name: http
      - containerPort: 50000
        name: agent
    volumeMounts:
      - name: jenkins-home
        mountPath: /var/jenkins_home

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: jenkins
  name: jenkins
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30808
    - port: 50000
      name: agent
      targetPort: 50000
      nodePort: 30500
  selector:
    name: jenkins
