apiVersion: v1
kind: ServiceAccount
metadata:
  name: def-ns-admin
  namespace: default
#---
#kind: Role
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  namespace: default
#  name: def-ns-admin-role
#rules:
#- apiGroups: ["*"]
#  resources: ["*"]
#  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: def-ns-admin
  namespace: default
subjects:
- kind: ServiceAccount
  name: def-ns-admin
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
