apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-0001
  labels:
    release: stable
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path:  "/volumes/v1"
    server: stor.ilinux.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-0002
  labels:
    release: stable
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path:  "/volumes/v2"
    server: stor.ilinux.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-0003
  labels:
    release: stable
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path:  "/volumes/v3"
    server: stor.ilinux.io
---
