apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rbd-0001
  labels:
    release: "stable"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  rbd:
    monitors:
      - 172.16.0.56:6789
      - 172.16.0.57:6789
      - 172.16.0.58:6789
    pool: kube
    image: pv-rbd-0001
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
