apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gold
  annotations:
     storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.16.0.56:6789,172.16.0.57:6789,172.16.0.58:6789  
  adminId: admin  
  adminSecretName: ceph-secret  
  adminSecretNamespace: kube-system
  pool: kube
  userId: admin  
  userSecretName: ceph-secret
