---
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 172.16.2.36
  ports:
  - port: 1
- addresses:
  - ip: 172.16.2.37
  ports:
  - port: 1
- addresses:
  - ip: 172.16.2.38
  ports:
  - port: 1
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: glusterfs
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://172.16.2.36:8080"
  restauthenabled: "false"
---
